### ISSUE TITLE
ReferenceError: console_error is not defined

### ISSUE THREAD

**Issue by scottsweb** [gadgetchnnel/lovelace-card-preloader#4]
Bit of an odd one this, just updated to version `0.107.7` of Home Assistant. Found out that this add-on is required to fix many of the UI bugs that have been introduced. Unfortunately I am seeing the following error in my console from this module:

`ReferenceError: console_error is not defined`

It is causing my Lovelave UI to go completely blank. Seems to happen across all browsers too. Any ideas what might be causing this?

**Comment by scottsweb** [comment]
Release `0.0.2` of this plugin seems to work as intented.

**Comment by gadgetchnnel** [comment]
@scottsweb I've just released 0.0.4 which should fix this, can you please give it a try?

**Comment by scottsweb** [comment]
Just tested and that seems to be working perfect. Thank you for taking a look so quickly.
